//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
  project: Project;
  projectConnection: ProjectConnection;
  team: Team;
  teamConnection: TeamConnection;
  event: Event;
  eventConnection: EventConnection;
  publication: Publication;
  publicationConnection: PublicationConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};


export type QueryEventArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
};


export type QueryPublicationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPublicationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicationFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
  project?: InputMaybe<ProjectFilter>;
  team?: InputMaybe<TeamFilter>;
  event?: InputMaybe<EventFilter>;
  publication?: InputMaybe<PublicationFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Project | Team | Event | Publication | Folder;

export type PageStats = {
  __typename?: 'PageStats';
  value: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type PageWhatWeDoCards = {
  __typename?: 'PageWhatWeDoCards';
  icon?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
};

export type PageValues = {
  __typename?: 'PageValues';
  icon?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
};

export type PageBenefits = {
  __typename?: 'PageBenefits';
  text: Scalars['String']['output'];
};

export type Page = Node & Document & {
  __typename?: 'Page';
  seoTitle: Scalars['String']['output'];
  seoDescription?: Maybe<Scalars['String']['output']>;
  heroTitle: Scalars['String']['output'];
  heroSubtitle?: Maybe<Scalars['String']['output']>;
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroCTA1Text?: Maybe<Scalars['String']['output']>;
  heroCTA1Link?: Maybe<Scalars['String']['output']>;
  heroCTA2Text?: Maybe<Scalars['String']['output']>;
  heroCTA2Link?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<PageStats>>>;
  whatWeDoTitle?: Maybe<Scalars['String']['output']>;
  whatWeDoSubtitle?: Maybe<Scalars['String']['output']>;
  whatWeDoCards?: Maybe<Array<Maybe<PageWhatWeDoCards>>>;
  currentProjectsTitle?: Maybe<Scalars['String']['output']>;
  currentProjectsSubtitle?: Maybe<Scalars['String']['output']>;
  ctaTitle?: Maybe<Scalars['String']['output']>;
  ctaSubtitle?: Maybe<Scalars['String']['output']>;
  ctaCTA1Text?: Maybe<Scalars['String']['output']>;
  ctaCTA1Link?: Maybe<Scalars['String']['output']>;
  ctaCTA2Text?: Maybe<Scalars['String']['output']>;
  ctaCTA2Link?: Maybe<Scalars['String']['output']>;
  missionTitle?: Maybe<Scalars['String']['output']>;
  missionContent?: Maybe<Scalars['String']['output']>;
  valuesTitle?: Maybe<Scalars['String']['output']>;
  values?: Maybe<Array<Maybe<PageValues>>>;
  teamTitle?: Maybe<Scalars['String']['output']>;
  teamSubtitle?: Maybe<Scalars['String']['output']>;
  formTitle?: Maybe<Scalars['String']['output']>;
  formSubtitle?: Maybe<Scalars['String']['output']>;
  sidebarTitle?: Maybe<Scalars['String']['output']>;
  benefits?: Maybe<Array<Maybe<PageBenefits>>>;
  connectEmail?: Maybe<Scalars['String']['output']>;
  connectTwitter?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type PageWhatWeDoCardsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PageValuesFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PageBenefitsFilter = {
  text?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageFilter = {
  seoTitle?: InputMaybe<StringFilter>;
  seoDescription?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  heroBadge?: InputMaybe<StringFilter>;
  heroCTA1Text?: InputMaybe<StringFilter>;
  heroCTA1Link?: InputMaybe<StringFilter>;
  heroCTA2Text?: InputMaybe<StringFilter>;
  heroCTA2Link?: InputMaybe<StringFilter>;
  stats?: InputMaybe<PageStatsFilter>;
  whatWeDoTitle?: InputMaybe<StringFilter>;
  whatWeDoSubtitle?: InputMaybe<StringFilter>;
  whatWeDoCards?: InputMaybe<PageWhatWeDoCardsFilter>;
  currentProjectsTitle?: InputMaybe<StringFilter>;
  currentProjectsSubtitle?: InputMaybe<StringFilter>;
  ctaTitle?: InputMaybe<StringFilter>;
  ctaSubtitle?: InputMaybe<StringFilter>;
  ctaCTA1Text?: InputMaybe<StringFilter>;
  ctaCTA1Link?: InputMaybe<StringFilter>;
  ctaCTA2Text?: InputMaybe<StringFilter>;
  ctaCTA2Link?: InputMaybe<StringFilter>;
  missionTitle?: InputMaybe<StringFilter>;
  missionContent?: InputMaybe<StringFilter>;
  valuesTitle?: InputMaybe<StringFilter>;
  values?: InputMaybe<PageValuesFilter>;
  teamTitle?: InputMaybe<StringFilter>;
  teamSubtitle?: InputMaybe<StringFilter>;
  formTitle?: InputMaybe<StringFilter>;
  formSubtitle?: InputMaybe<StringFilter>;
  sidebarTitle?: InputMaybe<StringFilter>;
  benefits?: InputMaybe<PageBenefitsFilter>;
  connectEmail?: InputMaybe<StringFilter>;
  connectTwitter?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type ProjectObjectives = {
  __typename?: 'ProjectObjectives';
  text: Scalars['String']['output'];
};

export type Project = Node & Document & {
  __typename?: 'Project';
  title: Scalars['String']['output'];
  status: Scalars['String']['output'];
  statusLabel?: Maybe<Scalars['String']['output']>;
  description: Scalars['String']['output'];
  objectives?: Maybe<Array<Maybe<ProjectObjectives>>>;
  timeline?: Maybe<Scalars['String']['output']>;
  network?: Maybe<Scalars['String']['output']>;
  milestone?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjectObjectivesFilter = {
  text?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ProjectFilter = {
  title?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  statusLabel?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  objectives?: InputMaybe<ProjectObjectivesFilter>;
  timeline?: InputMaybe<StringFilter>;
  network?: InputMaybe<StringFilter>;
  milestone?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type Team = Node & Document & {
  __typename?: 'Team';
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  initials?: Maybe<Scalars['String']['output']>;
  bio: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TeamFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  initials?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  order?: InputMaybe<NumberFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type Event = Node & Document & {
  __typename?: 'Event';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  time?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  status: Scalars['String']['output'];
  isFree?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  isFree?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type EventConnectionEdges = {
  __typename?: 'EventConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Event>;
};

export type EventConnection = Connection & {
  __typename?: 'EventConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventConnectionEdges>>>;
};

export type Publication = Node & Document & {
  __typename?: 'Publication';
  title: Scalars['String']['output'];
  type: Scalars['String']['output'];
  authors?: Maybe<Scalars['String']['output']>;
  journal?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  volume?: Maybe<Scalars['String']['output']>;
  doi?: Maybe<Scalars['String']['output']>;
  venue?: Maybe<Scalars['String']['output']>;
  venueDate?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PublicationFilter = {
  title?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  authors?: InputMaybe<StringFilter>;
  journal?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  volume?: InputMaybe<StringFilter>;
  doi?: InputMaybe<StringFilter>;
  venue?: InputMaybe<StringFilter>;
  venueDate?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PublicationConnectionEdges = {
  __typename?: 'PublicationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Publication>;
};

export type PublicationConnection = Connection & {
  __typename?: 'PublicationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PublicationConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePage: Page;
  createPage: Page;
  updateProject: Project;
  createProject: Project;
  updateTeam: Team;
  createTeam: Team;
  updateEvent: Event;
  createEvent: Event;
  updatePublication: Publication;
  createPublication: Publication;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationUpdateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationCreateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationUpdatePublicationArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicationMutation;
};


export type MutationCreatePublicationArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicationMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  project?: InputMaybe<ProjectMutation>;
  team?: InputMaybe<TeamMutation>;
  event?: InputMaybe<EventMutation>;
  publication?: InputMaybe<PublicationMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
  project?: InputMaybe<ProjectMutation>;
  team?: InputMaybe<TeamMutation>;
  event?: InputMaybe<EventMutation>;
  publication?: InputMaybe<PublicationMutation>;
};

export type PageStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type PageWhatWeDoCardsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PageValuesMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PageBenefitsMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type PageMutation = {
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  seoDescription?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroCTA1Text?: InputMaybe<Scalars['String']['input']>;
  heroCTA1Link?: InputMaybe<Scalars['String']['input']>;
  heroCTA2Text?: InputMaybe<Scalars['String']['input']>;
  heroCTA2Link?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<PageStatsMutation>>>;
  whatWeDoTitle?: InputMaybe<Scalars['String']['input']>;
  whatWeDoSubtitle?: InputMaybe<Scalars['String']['input']>;
  whatWeDoCards?: InputMaybe<Array<InputMaybe<PageWhatWeDoCardsMutation>>>;
  currentProjectsTitle?: InputMaybe<Scalars['String']['input']>;
  currentProjectsSubtitle?: InputMaybe<Scalars['String']['input']>;
  ctaTitle?: InputMaybe<Scalars['String']['input']>;
  ctaSubtitle?: InputMaybe<Scalars['String']['input']>;
  ctaCTA1Text?: InputMaybe<Scalars['String']['input']>;
  ctaCTA1Link?: InputMaybe<Scalars['String']['input']>;
  ctaCTA2Text?: InputMaybe<Scalars['String']['input']>;
  ctaCTA2Link?: InputMaybe<Scalars['String']['input']>;
  missionTitle?: InputMaybe<Scalars['String']['input']>;
  missionContent?: InputMaybe<Scalars['String']['input']>;
  valuesTitle?: InputMaybe<Scalars['String']['input']>;
  values?: InputMaybe<Array<InputMaybe<PageValuesMutation>>>;
  teamTitle?: InputMaybe<Scalars['String']['input']>;
  teamSubtitle?: InputMaybe<Scalars['String']['input']>;
  formTitle?: InputMaybe<Scalars['String']['input']>;
  formSubtitle?: InputMaybe<Scalars['String']['input']>;
  sidebarTitle?: InputMaybe<Scalars['String']['input']>;
  benefits?: InputMaybe<Array<InputMaybe<PageBenefitsMutation>>>;
  connectEmail?: InputMaybe<Scalars['String']['input']>;
  connectTwitter?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ProjectObjectivesMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  statusLabel?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  objectives?: InputMaybe<Array<InputMaybe<ProjectObjectivesMutation>>>;
  timeline?: InputMaybe<Scalars['String']['input']>;
  network?: InputMaybe<Scalars['String']['input']>;
  milestone?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TeamMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  initials?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type EventMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  isFree?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PublicationMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  authors?: InputMaybe<Scalars['String']['input']>;
  journal?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  volume?: InputMaybe<Scalars['String']['input']>;
  doi?: InputMaybe<Scalars['String']['input']>;
  venue?: InputMaybe<Scalars['String']['input']>;
  venueDate?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PagePartsFragment = { __typename: 'Page', seoTitle: string, seoDescription?: string | null, heroTitle: string, heroSubtitle?: string | null, heroBadge?: string | null, heroCTA1Text?: string | null, heroCTA1Link?: string | null, heroCTA2Text?: string | null, heroCTA2Link?: string | null, whatWeDoTitle?: string | null, whatWeDoSubtitle?: string | null, currentProjectsTitle?: string | null, currentProjectsSubtitle?: string | null, ctaTitle?: string | null, ctaSubtitle?: string | null, ctaCTA1Text?: string | null, ctaCTA1Link?: string | null, ctaCTA2Text?: string | null, ctaCTA2Link?: string | null, missionTitle?: string | null, missionContent?: string | null, valuesTitle?: string | null, teamTitle?: string | null, teamSubtitle?: string | null, formTitle?: string | null, formSubtitle?: string | null, sidebarTitle?: string | null, connectEmail?: string | null, connectTwitter?: string | null, body?: any | null, stats?: Array<{ __typename: 'PageStats', value: string, label: string } | null> | null, whatWeDoCards?: Array<{ __typename: 'PageWhatWeDoCards', icon?: string | null, title: string, description: string } | null> | null, values?: Array<{ __typename: 'PageValues', icon?: string | null, title: string, description: string } | null> | null, benefits?: Array<{ __typename: 'PageBenefits', text: string } | null> | null };

export type ProjectPartsFragment = { __typename: 'Project', title: string, status: string, statusLabel?: string | null, description: string, timeline?: string | null, network?: string | null, milestone?: string | null, order?: number | null, body?: any | null, objectives?: Array<{ __typename: 'ProjectObjectives', text: string } | null> | null };

export type TeamPartsFragment = { __typename: 'Team', name: string, role: string, initials?: string | null, bio: string, image?: string | null, order?: number | null, body?: any | null };

export type EventPartsFragment = { __typename: 'Event', title: string, date: string, time?: string | null, location?: string | null, status: string, isFree?: boolean | null, description?: string | null, url?: string | null, order?: number | null, body?: any | null };

export type PublicationPartsFragment = { __typename: 'Publication', title: string, type: string, authors?: string | null, journal?: string | null, year?: string | null, volume?: string | null, doi?: string | null, venue?: string | null, venueDate?: string | null, order?: number | null, body?: any | null };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, seoTitle: string, seoDescription?: string | null, heroTitle: string, heroSubtitle?: string | null, heroBadge?: string | null, heroCTA1Text?: string | null, heroCTA1Link?: string | null, heroCTA2Text?: string | null, heroCTA2Link?: string | null, whatWeDoTitle?: string | null, whatWeDoSubtitle?: string | null, currentProjectsTitle?: string | null, currentProjectsSubtitle?: string | null, ctaTitle?: string | null, ctaSubtitle?: string | null, ctaCTA1Text?: string | null, ctaCTA1Link?: string | null, ctaCTA2Text?: string | null, ctaCTA2Link?: string | null, missionTitle?: string | null, missionContent?: string | null, valuesTitle?: string | null, teamTitle?: string | null, teamSubtitle?: string | null, formTitle?: string | null, formSubtitle?: string | null, sidebarTitle?: string | null, connectEmail?: string | null, connectTwitter?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'PageStats', value: string, label: string } | null> | null, whatWeDoCards?: Array<{ __typename: 'PageWhatWeDoCards', icon?: string | null, title: string, description: string } | null> | null, values?: Array<{ __typename: 'PageValues', icon?: string | null, title: string, description: string } | null> | null, benefits?: Array<{ __typename: 'PageBenefits', text: string } | null> | null } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, seoTitle: string, seoDescription?: string | null, heroTitle: string, heroSubtitle?: string | null, heroBadge?: string | null, heroCTA1Text?: string | null, heroCTA1Link?: string | null, heroCTA2Text?: string | null, heroCTA2Link?: string | null, whatWeDoTitle?: string | null, whatWeDoSubtitle?: string | null, currentProjectsTitle?: string | null, currentProjectsSubtitle?: string | null, ctaTitle?: string | null, ctaSubtitle?: string | null, ctaCTA1Text?: string | null, ctaCTA1Link?: string | null, ctaCTA2Text?: string | null, ctaCTA2Link?: string | null, missionTitle?: string | null, missionContent?: string | null, valuesTitle?: string | null, teamTitle?: string | null, teamSubtitle?: string | null, formTitle?: string | null, formSubtitle?: string | null, sidebarTitle?: string | null, connectEmail?: string | null, connectTwitter?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'PageStats', value: string, label: string } | null> | null, whatWeDoCards?: Array<{ __typename: 'PageWhatWeDoCards', icon?: string | null, title: string, description: string } | null> | null, values?: Array<{ __typename: 'PageValues', icon?: string | null, title: string, description: string } | null> | null, benefits?: Array<{ __typename: 'PageBenefits', text: string } | null> | null } | null } | null> | null } };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, title: string, status: string, statusLabel?: string | null, description: string, timeline?: string | null, network?: string | null, milestone?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, objectives?: Array<{ __typename: 'ProjectObjectives', text: string } | null> | null } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, title: string, status: string, statusLabel?: string | null, description: string, timeline?: string | null, network?: string | null, milestone?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, objectives?: Array<{ __typename: 'ProjectObjectives', text: string } | null> | null } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, name: string, role: string, initials?: string | null, bio: string, image?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, name: string, role: string, initials?: string | null, bio: string, image?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EventQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventQuery = { __typename?: 'Query', event: { __typename: 'Event', id: string, title: string, date: string, time?: string | null, location?: string | null, status: string, isFree?: boolean | null, description?: string | null, url?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
}>;


export type EventConnectionQuery = { __typename?: 'Query', eventConnection: { __typename?: 'EventConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventConnectionEdges', cursor: string, node?: { __typename: 'Event', id: string, title: string, date: string, time?: string | null, location?: string | null, status: string, isFree?: boolean | null, description?: string | null, url?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PublicationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PublicationQuery = { __typename?: 'Query', publication: { __typename: 'Publication', id: string, title: string, type: string, authors?: string | null, journal?: string | null, year?: string | null, volume?: string | null, doi?: string | null, venue?: string | null, venueDate?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PublicationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicationFilter>;
}>;


export type PublicationConnectionQuery = { __typename?: 'Query', publicationConnection: { __typename?: 'PublicationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PublicationConnectionEdges', cursor: string, node?: { __typename: 'Publication', id: string, title: string, type: string, authors?: string | null, journal?: string | null, year?: string | null, volume?: string | null, doi?: string | null, venue?: string | null, venueDate?: string | null, order?: number | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  seoTitle
  seoDescription
  heroTitle
  heroSubtitle
  heroBadge
  heroCTA1Text
  heroCTA1Link
  heroCTA2Text
  heroCTA2Link
  stats {
    __typename
    value
    label
  }
  whatWeDoTitle
  whatWeDoSubtitle
  whatWeDoCards {
    __typename
    icon
    title
    description
  }
  currentProjectsTitle
  currentProjectsSubtitle
  ctaTitle
  ctaSubtitle
  ctaCTA1Text
  ctaCTA1Link
  ctaCTA2Text
  ctaCTA2Link
  missionTitle
  missionContent
  valuesTitle
  values {
    __typename
    icon
    title
    description
  }
  teamTitle
  teamSubtitle
  formTitle
  formSubtitle
  sidebarTitle
  benefits {
    __typename
    text
  }
  connectEmail
  connectTwitter
  body
}
    `;
export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  title
  status
  statusLabel
  description
  objectives {
    __typename
    text
  }
  timeline
  network
  milestone
  order
  body
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  name
  role
  initials
  bio
  image
  order
  body
}
    `;
export const EventPartsFragmentDoc = gql`
    fragment EventParts on Event {
  __typename
  title
  date
  time
  location
  status
  isFree
  description
  url
  order
  body
}
    `;
export const PublicationPartsFragmentDoc = gql`
    fragment PublicationParts on Publication {
  __typename
  title
  type
  authors
  journal
  year
  volume
  doi
  venue
  venueDate
  order
  body
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export const EventDocument = gql`
    query event($relativePath: String!) {
  event(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventParts
  }
}
    ${EventPartsFragmentDoc}`;
export const EventConnectionDocument = gql`
    query eventConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventFilter) {
  eventConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventParts
      }
    }
  }
}
    ${EventPartsFragmentDoc}`;
export const PublicationDocument = gql`
    query publication($relativePath: String!) {
  publication(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PublicationParts
  }
}
    ${PublicationPartsFragmentDoc}`;
export const PublicationConnectionDocument = gql`
    query publicationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PublicationFilter) {
  publicationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PublicationParts
      }
    }
  }
}
    ${PublicationPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      },
    event(variables: EventQueryVariables, options?: C): Promise<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}> {
        return requester<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}, EventQueryVariables>(EventDocument, variables, options);
      },
    eventConnection(variables?: EventConnectionQueryVariables, options?: C): Promise<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}> {
        return requester<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}, EventConnectionQueryVariables>(EventConnectionDocument, variables, options);
      },
    publication(variables: PublicationQueryVariables, options?: C): Promise<{data: PublicationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationQueryVariables, query: string}> {
        return requester<{data: PublicationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationQueryVariables, query: string}, PublicationQueryVariables>(PublicationDocument, variables, options);
      },
    publicationConnection(variables?: PublicationConnectionQueryVariables, options?: C): Promise<{data: PublicationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationConnectionQueryVariables, query: string}> {
        return requester<{data: PublicationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationConnectionQueryVariables, query: string}, PublicationConnectionQueryVariables>(PublicationConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.0/content/9e681379-aa9c-4f09-a381-27ea1a4f71aa/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  